Add constructors and mutators useful downstream
ORNL-QCI/qiree pull request #5
Opened 2024-06-30 17:47 UTC by ausbin

These are useful for me downstream in the Qwerty compiler/runtime.

It would be nicer to pass the accelerator and shots as arguments to `qiree::Executor` somehow, but this solves my immediate engineering problem.

### Testing

Once rebased against #4, this builds and passes `ctest`. I previously tested this code end-to-end in the Qwerty runtime but the code is in a state where it will be tough to do that again.

2024-07-31 16:00 UTC, sethrj requested changes

2024-07-31 16:00 UTC, sethrj commented on src/qirxacc/XaccQuantum.cc
> +    set_accelerator_and_shots(accel_name, shots);
Is there a reason to "create and then initialize" the class like this? Best practices say initialization should take place at construction. It improves performance sometimes, but more importantly it helps "reasoning" about the state of the code because you don't have to worry about some other part of the code changing the state of an object that you got.

2024-10-08 03:55 UTC, ausbin commented on src/qirxacc/XaccQuantum.cc
> +    set_accelerator_and_shots(accel_name, shots);
Okay, I modified it to duplicate that chunk of code

2024-12-18 14:08 UTC, sethrj requested changes

2024-12-18 14:08 UTC, sethrj commented on src/qirxacc/XaccQuantum.cc
> +void XaccQuantum::set_accelerator_and_shots(
This should be done at initialization time (which the constructor does) rather than at some arbitrary point after construction (where it could be in an unspecified state, like in the middle of a calculation). There shouldn't be any need for delayed partial initialization (bad practice in C++); can you explain the use case?

Also please remember to run clang-format.

2024-12-18 14:08 UTC, sethrj commented on src/qiree/Module.cc
> +Module::Module(UPModule&& module, std::string const& entrypoint)
Doesn't QIR require a function to be specified as an entry point? or is this for the case where you have more than one entry point in a QIR file (and is that legal?)

2024-12-18 17:01 UTC, ausbin commented on src/qiree/Module.cc
> +Module::Module(UPModule&& module, std::string const& entrypoint)
> or is this for the case where you have more than one entry point in a QIR file

Exactly, yeah. Sometimes the Qwerty runtime can produce a QIR module with multiple entry points.

> (and is that legal?)

I couldn't anywhere that [the spec][3] says that multiple entry points are allowed, but it doesn't seem to say that only one entry point is allowed either.

I learned this was possible from reading the qir-runner source code: [1][1], [2][2]. The tl;dr is that if there is one entry point, qir-runner uses it, but otherwise they require specifying the name of the entry point to use.

[1]: https://github.com/qir-alliance/qir-runner/blob/2ab1eb5cb207b444d6e7b0b261e1661cb65363a3/runner/src/lib.rs#L201
[2]: https://github.com/qir-alliance/qir-runner/blob/2ab1eb5cb207b444d6e7b0b261e1661cb65363a3/runner/tests/tests.rs#L215-L243
[3]: https://github.com/qir-alliance/qir-spec/blob/8b3fd47b7b70122a104e24733ef9de911576f7d6/specification/under_development/profiles/Base_Profile.md#entry-point-definition

2024-12-18 17:08 UTC, ausbin commented on src/qiree/Module.cc
> +Module::Module(UPModule&& module, std::string const& entrypoint)
Also, there's already a similar constructor overload that takes an entrypoint name, just with a filename instead of an `llvm::Module`: https://github.com/ORNL-QCI/qiree/blob/9c1ff4c7c784251c0a13d04257f7eb1ff6cfbf74/src/qiree/Module.cc#L129

2024-12-18 19:00 UTC, ausbin commented on src/qirxacc/XaccQuantum.cc
> +void XaccQuantum::set_accelerator_and_shots(
I added this because `XaccQuantum` effectively needs to be used as a singleton right now because `xacc::Finalize()` does not clean up the state of XACC properly, meaning you cannot currently create two consecutive `XaccQuantum` instances.

<details>
<summary>Details (if you're interested)</summary>
To see this in action, you can add this:

```diff
$ git diff
diff --git a/app/qir-xacc.cc b/app/qir-xacc.cc
index 383fb6f..2bb6156 100644
--- a/app/qir-xacc.cc
+++ b/app/qir-xacc.cc
@@ -36,6 +36,11 @@ void run(std::string const& filename,
     // Load the input
     Executor execute{Module{filename}};
 
+    {
+        XaccQuantum xacc_temp(std::cout, accel_name, num_shots);
+        (void)xacc_temp;
+    }
+
     // Set up XACC
     XaccQuantum xacc(std::cout, accel_name, num_shots);
     std::unique_ptr<RuntimeInterface> rt;
```

Then, when running a trivial example:
```
$ gdb --args qir-xacc -i bell.ll -a qpp
[snip]
terminate called after throwing an instance of 'std::runtime_error'
  what():  The bundle context is no longer valid
[snip]
(gdb) bt
[snip]
#10 0x00007ffff7aae2dd in cppmicroservices::BundleContext::GetServiceReferences<xacc::OptionsProvider> (this=0x55555856b208, filter="")
    at /home/austin/Documents/school/gatech/grad/xacc/xacc/tpls/cppmicroservices/framework/include/cppmicroservices/BundleContext.h:445
#11 0x00007ffff7aabe65 in xacc::ServiceRegistry::getServices<xacc::OptionsProvider> (this=0x55555856b1e0)
    at /home/austin/Documents/school/gatech/grad/xacc/xacc/xacc/service/ServiceRegistry.hpp:161
#12 0x00007ffff7aa741d in xacc::ServiceRegistry::getRegisteredOptions[abi:cxx11]() (this=0x55555856b1e0)
    at /home/austin/Documents/school/gatech/grad/xacc/xacc/xacc/service/ServiceRegistry.hpp:187
#13 0x00007ffff7aa6268 in xacc::getRegisteredOptions[abi:cxx11]() ()
    at /home/austin/Documents/school/gatech/grad/xacc/xacc/xacc/service/xacc_service.cpp:74
#14 0x00007ffff7ae41b8 in xacc::CLIParser::parse (this=0x7ffff00ef4c0, argc=1, argv=0x5555585aa7c0)
    at /home/austin/Documents/school/gatech/grad/xacc/xacc/xacc/utils/CLIParser.cpp:48
#15 0x00007ffff7b5a718 in xacc::Initialize (arc=1, arv=0x5555585aa7c0) at /home/austin/Documents/school/gatech/grad/xacc/xacc/xacc/xacc.cpp:92
#16 0x00007ffff7b5a2ab in xacc::Initialize (argv=std::vector of length 1, capacity 1 = {...})
    at /home/austin/Documents/school/gatech/grad/xacc/xacc/xacc/xacc.cpp:60
#17 0x00007ffff7b5a329 in xacc::Initialize () at /home/austin/Documents/school/gatech/grad/xacc/xacc/xacc/xacc.cpp:63
#18 0x0000555555849dd8 in qiree::XaccQuantum::XaccQuantum (this=0x7fffffffd120, os=..., accel_name="qpp", shots=1024, __in_chrg=<optimized out>,
    __vtt_parm=<optimized out>) at /home/austin/Documents/school/gatech/grad/qsvt/qiree/src/qirxacc/XaccQuantum.cc:46
#19 0x00005555557f339f in qiree::app::run (filename="bell.ll", accel_name="qpp", num_shots=1024, print_accelbuf=true, group_tuples=false)
    at /home/austin/Documents/school/gatech/grad/qsvt/qiree/app/qir-xacc.cc:45
#20 0x00005555557f3a27 in main (argc=5, argv=0x7fffffffd9b8) at /home/austin/Documents/school/gatech/grad/qsvt/qiree/app/qir-xacc.cc:98
```
</details>

I just opened this XACC PR to fix this problem for the sake of future QIR-EE users: ORNL-QCI/xacc#63. I removed this setter from this PR, but I will keep it in my fork because I do not want to re-do `xacc::Initialize()` and `xacc::Finalize()` several times

2024-12-18 19:18 UTC, sethrj commented on src/qiree/Module.cc
> +Module::Module(UPModule&& module, std::string const& entrypoint)
You're right, and I forgot about that function! I wonder if we need to restructure so that the `Executor::operator()` takes the entry point function name since one module has to be correspond exactly to a single executor, and if we have multiple entry points in one module it would be better not to have to recreate the module each time?

2024-12-18 19:18 UTC, sethrj commented on src/qirxacc/XaccQuantum.cc
> +void XaccQuantum::set_accelerator_and_shots(
All right, makes sense since xacc has singletons. I'd *prefer* that we hide that kind of bad behavior in our implementation: for example, we could make a private helper class that cleanly manages XACC cleanup/teardown and would be called in the constructor/destructor. It's probably not a bad idea to do that anyway, since we've got this object oriented facade built on top of a singleton class: creating two different XaccQuantum classes simultaneously would wreak all sorts of havoc.

2024-12-18 19:19 UTC, sethrj approved these changes

2024-12-18 19:50 UTC, merged